name: Build Hands

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Initialize
      uses: actions/checkout@v2
    - name: Cache Bazel
      uses: actions/cache@v2
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}

    - name: Build binary
      run: |
        pip install numpy
        bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

    - name: The job has succeeded
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: hand_tracking_cpu
        path: bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu

    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30

