name: PullRequest

on: [pull_request]

jobs:
  buildTest:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.0
      - name: Install prerequisite
        run: | 
          brew install opencv@3
          brew install python
          python --version
          pip3 install --user six
      - name: Build project
        run: |
          export ANDROID_HOME=/Users/runner/Library/Android/sdk
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle 
          bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar
      - name: Show result
        run: git status
      - name: Search AAR
        run: find bazel-bin/mediapipe/ -name *.aar | xargs ls -la
      - name: Archive AAR
        uses: actions/upload-artifact@v2.2.1
        if: ${{ always() }}
        with:
          name: AAR-library
          path: bazel-bin/mediapipe//examples/android/src/java/com/google/mediapipe/apps/**/*.aar
